// eslint.config.js — Minimal ESLint config for bug-catching, not style.
// Uses ESLint v9 flat config format.

export default [
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "libs/**",
      "vendor/**",
      "stubs/**",
      "tests/**",
      "eslint.config.js",
      "webpack.config.js",
      "mathjax-entry.js",
      "scripts/**",
    ],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        TextDecoder: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        Node: "readonly",
        HTMLElement: "readonly",
        matchMedia: "readonly",
        requestAnimationFrame: "readonly",
        self: "readonly",
        alert: "readonly",
        confirm: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        MathJaxBundle: "readonly",
        // Chrome extension APIs
        chrome: "readonly",
        // Shared globals from panel script chain
        GHOSTWRITER_DEFAULTS: "readonly",
        QUICKFLASH_PROMPTS: "readonly",
        // panel-markdown.js globals
        makeBackLinkHTML: "readonly",
        escapeHtml: "readonly",
        extractMathSegments: "readonly",
        restoreMathSegments: "readonly",
        renderMarkdownToHtml: "readonly",
        convertLatexToAnki: "readonly",
        markdownRendererState: "readonly",
        getMarkdownRenderer: "readonly",
        // panel-ai-templates.js globals
        buildSimpleAITemplatePrompt: "readonly",
        buildSimpleAITemplatePromptWithMathRule: "readonly",
        buildDefinitionAITemplatePrompt: "readonly",
        buildResearchPaperAITemplatePrompt: "readonly",
        buildLegacyResearchPaperAITemplatePrompt: "readonly",
        upgradeDefinitionPromptIfNeeded: "readonly",
        upgradeResearchPaperPromptIfNeeded: "readonly",
        DEFAULT_AI_TEMPLATES: "readonly",
        TEMPLATE_UPDATE_MODES: "readonly",
        DEFAULT_TEMPLATE_UPDATE_MODE: "readonly",
        cloneAITemplateEntry: "readonly",
        cloneDefaultAITemplates: "readonly",
        getTemplateUpdateMode: "readonly",
        normalizeStoredAITemplate: "readonly",
        templatesMatch: "readonly",
        reconcileAiTemplatesWithDefaults: "readonly",
        populateAiTemplateSelect: "readonly",
        getAiTemplateList: "readonly",
        ensureAiTemplatesLoaded: "readonly",
        buildFallbackAiPrompt: "readonly",
        aiTemplates: "writable",
        aiTemplatesLoaded: "writable",
      },
    },
    rules: {
      // Catch real bugs
      "no-undef": "warn",
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "warn",
      "no-constant-condition": "warn",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "eqeqeq": ["warn", "smart"],
      "no-throw-literal": "warn",
      // Off — too noisy for this codebase
      "no-empty": "off",
      "no-fallthrough": "off",
      "no-implicit-globals": "off",
    },
  },
];
